### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by abolotsko** [karolyi/py3-validate-email#2]
Hi, 

I just tested the package and it keeps throwing the following error with the sample code that was provided. I am running Python 3.7 and the package version is up to date.

`C:\Users\workspace\automation\venv\Scripts\python.exe C:/Users/workspace/automation/email_validation/email_val.py
Traceback (most recent call last):
  File "C:/Users/workspace/automation/email_validation/email_val.py", line 1, in <module>
    from validate_email import validate_email
  File "C:\Users\workspace\automation\venv\lib\site-packages\validate_email\__init__.py", line 1, in <module>
    from .validate_email import validate_email
  File "C:\Users\workspace\automation\venv\lib\site-packages\validate_email\validate_email.py", line 3, in <module>
    from .domainlist_check import domainlist_check
  File "C:\Users\workspace\automation\venv\lib\site-packages\validate_email\domainlist_check.py", line 3, in <module>
    from .updater import BLACKLIST_FILE_PATH, BlacklistUpdater
  File "C:\Users\workspace\automation\venv\lib\site-packages\validate_email\updater.py", line 1, in <module>
    from fcntl import LOCK_EX, LOCK_UN, flock
ModuleNotFoundError: No module named 'fcntl'`

**Comment by karolyi** [comment]
It seems to me you're using windows. the `fnctl` module is missing there.

Try it on Linux (WSL is a good candidate).
