### ISSUE TITLE
Install py3-validate-email issue

### ISSUE THREAD

**Issue by tonybastienricher** [karolyi/py3-validate-email#21]
Hello, I have an issue when I run "pip install py3-validate-email"
```
> pip install py3-validate-email
Collecting py3-validate-email
  Using cached py3-validate-email-0.2.8.tar.gz (10 kB)
Requirement already satisfied: dnspython~=1.16 in /Users/tonyricher/.local/share/virtualenvs/python-IceqmoFh/lib/python
3.8/site-packages (from py3-validate-email) (1.16.0)
Requirement already satisfied: idna~=2.8 in /Users/tonyricher/.local/share/virtualenvs/python-IceqmoFh/lib/python3.8/si
te-packages (from py3-validate-email) (2.9)
Requirement already satisfied: filelock~=3.0 in /Users/tonyricher/.local/share/virtualenvs/python-IceqmoFh/lib/python3.
8/site-packages (from py3-validate-email) (3.0.12)
Building wheels for collected packages: py3-validate-email
  Building wheel for py3-validate-email (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/tonyricher/.local/share/virtualenvs/python-IceqmoFh/bin/python -u -c 'import sys, setuptools, tokeni
ze; sys.argv[0] = '"'"'/private/var/folders/bf/8d8nnwtd2p5141vk9dt8tb8c0000gn/T/pip-install-lqtgfwbl/py3-validate-email
/setup.py'"'"'; __file__='"'"'/private/var/folders/bf/8d8nnwtd2p5141vk9dt8tb8c0000gn/T/pip-install-lqtgfwbl/py3-validat
e-email/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n
'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/bf/8d8nnwtd2p5141vk
9dt8tb8c0000gn/T/pip-wheel-x0js53ir
       cwd: /private/var/folders/bf/8d8nnwtd2p5141vk9dt8tb8c0000gn/T/pip-install-lqtgfwbl/py3-validate-email/
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/validate_email
  copying validate_email/regex_check.py -> build/lib/validate_email
  copying validate_email/mx_check.py -> build/lib/validate_email
  copying validate_email/constants.py -> build/lib/validate_email
  copying validate_email/__init__.py -> build/lib/validate_email
  copying validate_email/updater.py -> build/lib/validate_email
  copying validate_email/email_address.py -> build/lib/validate_email
  copying validate_email/validate_email.py -> build/lib/validate_email
  copying validate_email/domainlist_check.py -> build/lib/validate_email
  copying validate_email/exceptions.py -> build/lib/validate_email
  downloading blacklist to /private/var/folders/bf/8d8nnwtd2p5141vk9dt8tb8c0000gn/T/pip-install-lqtgfwbl/py3-validate-email/build/lib/validate_email/data/blacklist.txt
  error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
  ----------------------------------------
  ERROR: Failed building wheel for py3-validate-email
  Running setup.py clean for py3-validate-email
Failed to build py3-validate-email
Installing collected packages: py3-validate-email
    Running setup.py install for py3-validate-email ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/tonyricher/.local/share/virtualenvs/python-IceqmoFh/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bf/8d8nnwtd2p5141vk9dt8tb8c0000gn/T/pip-install-lqtgfwbl/py3-validate-email/setup.py'"'"'; __file__='"'"'/private/var/folders/bf/8d8nnwtd2p5141vk9dt8tb8c0000gn/T/pip-install-lqtgfwbl/py3-validate-email/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bf/8d8nnwtd2p5141vk9dt8tb8c0000gn/T/pip-record-kutwh01b/install-record.txt --single-version-externally-managed --compile --install-headers /Users/tonyricher/.local/share/virtualenvs/python-IceqmoFh/include/site/python3.8/py3-validate-email
         cwd: /private/var/folders/bf/8d8nnwtd2p5141vk9dt8tb8c0000gn/T/pip-install-lqtgfwbl/py3-validate-email/
    Complete output (17 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/validate_email
    copying validate_email/regex_check.py -> build/lib/validate_email
    copying validate_email/mx_check.py -> build/lib/validate_email
    copying validate_email/constants.py -> build/lib/validate_email
    copying validate_email/__init__.py -> build/lib/validate_email
    copying validate_email/updater.py -> build/lib/validate_email
```
I don't know why .. Could you help me ?

**Comment by karolyi** [comment]
this seems to me a certificate validation error. are you installing within a docker environment?

**Comment by tonybastienricher** [comment]
No. I have juste pipenv for virtualize my environment

**Comment by karolyi** [comment]
I can't reproduce this error. All I can think is the certificates on your machine you are trying to install this module on, are outdated. My other guess was you use docker that has no certs at all, which is not the case.

Can you make this error somehow reproducible?

**Comment by karolyi** [comment]
Please try to execute this code in your venv with python:
```python
from urllib.request import Request, urlopen
request = Request(url='https://raw.githubusercontent.com/martenson/disposable-email-domains/master/disposable_email_blocklist.conf')
response = urlopen(url=request)
```

Does it show any errors?

**Comment by karolyi** [comment]
Also, a quick duckduckgo of the error in your issue search resulted in this:
https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate

**Comment by tonybastienricher** [comment]
Same [SSL: CERTIFICATE_VERIFY_FAILED] error : 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1399, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certifi
cate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
```

**Comment by tonybastienricher** [comment]
I reinstalled python 3.8 and ran the script 'Install Certificates.command'.
It's working 🤟
Thanks @karolyi

**Comment by karolyi** [comment]
You're welcome. If this problem pops up countless time again, depending on [`certifi`](https://pypi.org/project/certifi/) (a package for root and intermediate certificates) might be a good idea.
