### ISSUE TITLE
Python 3.7+ SMTP Value Error

### ISSUE THREAD

**Issue by SergeyKons** [karolyi/py3-validate-email#50]
Hi! We found another bug in one of our staging servers.

We use Python 3.8 and call SMTP. connect without specifying hostname in SMTP class constructor, we will get Value Error with this traceback

```
Traceback (most recent call last):
  File "/home/sergeyshevch/py3-validate-email/tests/test_mx_check.py", line 79, in test_gmail_false_positives
    mx_check(EmailAddress("saintka44@yandex.ru"), debug=True, skip_smtp=False, helo_host="smartsuite.com")
  File "/home/sergeyshevch/py3-validate-email/validate_email/mx_check.py", line 196, in mx_check
    return _check_mx_records(
  File "/home/sergeyshevch/py3-validate-email/validate_email/mx_check.py", line 162, in _check_mx_records
    found_ambigious |= _check_one_mx(
  File "/home/sergeyshevch/py3-validate-email/validate_email/mx_check.py", line 139, in _check_one_mx
    _smtp_converse(
  File "/home/sergeyshevch/py3-validate-email/validate_email/mx_check.py", line 120, in _smtp_converse
    _smtp_ehlo_tls(smtp=smtp, helo_host=helo_host)
  File "/home/sergeyshevch/py3-validate-email/validate_email/mx_check.py", line 81, in _smtp_ehlo_tls
    code, message = smtp.ehlo(name=helo_host)
  File "/home/sergeyshevch/.pyenv/versions/3.8.6/lib/python3.8/smtplib.py", line 774, in starttls
    self.sock = context.wrap_socket(self.sock,
  File "/home/sergeyshevch/.pyenv/versions/3.8.6/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/sergeyshevch/.pyenv/versions/3.8.6/lib/python3.8/ssl.py", line 1031, in _create
    self._sslobj = self._context._wrap_socket(
ValueError: server_hostname cannot be an empty string or start with a leading dot.

----------------------------------------------------------------------
Ran 16 tests in 2.496s
```

Related: https://github.com/ansible/ansible/pull/44552
I will create PR today to fix it

**Comment by SergeyKons** [comment]
@karolyi I was created PR that will fix this issue. Can you look at it? #51

**Comment by reinhard-mueller** [comment]
It should be correct that the `SMTP` object is created without a `host` parameter, as the hostname is set two lines below with the `smtp.connect` command. Can you find out what you get returned from the `smtp.connect(host=mx_record)` call?

**Comment by SergeyKons** [comment]
@reinhard-mueller 
```
> /home/sergeyshevch/py3-validate-email/validate_email/mx_check.py(118)_smtp_converse()
-> if code >= 400:
(Pdb) message
b'vla1-2e54448a8a0c.qloud-c.yandex.net (Want to use Yandex.Mail for your domain? Visit http://pdd.yandex.ru)'
(Pdb) code
220
(Pdb) smtp._host
''
(Pdb) c
17:19:34.733468 send: 'ehlo gmail.com\r\n'
17:19:34.808111 reply: b'250-vla1-2e54448a8a0c.qloud-c.yandex.net\r\n'
17:19:34.808303 reply: b'250-8BITMIME\r\n'
17:19:34.808347 reply: b'250-PIPELINING\r\n'
17:19:34.808473 reply: b'250-SIZE 42991616\r\n'
17:19:34.808576 reply: b'250-STARTTLS\r\n'
17:19:34.808659 reply: b'250-DSN\r\n'
17:19:34.808684 reply: b'250 ENHANCEDSTATUSCODES\r\n'
17:19:34.808719 reply: retcode (250); Msg: b'vla1-2e54448a8a0c.qloud-c.yandex.net\n8BITMIME\nPIPELINING\nSIZE 42991616\nSTARTTLS\nDSN\nENHANCEDSTATUSCODES'
17:19:34.809596 send: 'STARTTLS\r\n'
17:19:34.880381 reply: b'220 Go ahead\r\n'
17:19:34.880610 reply: retcode (220); Msg: b'Go ahead'
17:19:34.893348 send: 'QUIT\r\n'
ERROR
```

**Comment by SergeyKons** [comment]
_host attribute is not set in SMTP class. So we will get an error when we call smtp.starttls()

**Comment by reinhard-mueller** [comment]
Okay, this is a bug in Python's smtplib - SMTP.connect() forgets to set self._host. I'll post a alternative patch.

**Comment by SergeyKons** [comment]
Ok, It will be great.
Don't like to use git fork as a package source.

**Comment by karolyi** [comment]
@reinhard-mueller yeah I remember having this issue, hence my other solution... but with so many other things in my head, I quickly forgot about this one.

the users are the best testers though.

**Comment by reinhard-mueller** [comment]
@SergeyKons can you test whether the fix in #52 works for you?

**Comment by reinhard-mueller** [comment]
FWIW, the point is that if you pass the hostname to the SMTP constructor, it will immediately make the connection - before the debug level is properly set - and it will generate an exception instead of returning code and message of the server's answer.

**Comment by SergeyKons** [comment]
I will check in at 5 min

**Comment by SergeyKons** [comment]
@reinhard-mueller Yes it works correctlyly

**Comment by karolyi** [comment]
I'll make a quick release.

**Comment by SergeyKons** [comment]
@karolyi It will be great!
